"""Loader for ``bible_books.json``, the English-name -> book_number source of truth.

The repo-root file on ``main`` is the only copy.  ``index.json`` (generated by
``scripts/generate_index.py``) records its hash under ``meta.books_sot`` so any
copy can be validated.  Resolution order:

1. an explicit path (caller's responsibility, not validated);
2. the repo-root file when running from a checkout, validated against the
   local ``index.json`` (a mismatch only warns: you may be mid-edit);
3. download from ``main`` and validate against the remote ``index.json``
   (a mismatch raises).  A validated copy is cached on disk and used if the
   network is unavailable later.
"""

from __future__ import annotations

import hashlib
import json
import os
import urllib.request
import warnings
from functools import lru_cache
from pathlib import Path

RAW_BASE = "https://raw.githubusercontent.com/develop4God/bible_versions/main"
BOOKS_URL = f"{RAW_BASE}/bible_books.json"
INDEX_URL = f"{RAW_BASE}/index.json"
FETCH_TIMEOUT = 10


class BooksSotError(RuntimeError):
    """The books source of truth could not be loaded or failed validation."""


def content_hash(data: bytes) -> str:
    """Same scheme as ``generate_index.file_hash``: sha256, first 16 hex chars."""
    return hashlib.sha256(data).hexdigest()[:16]


def _checkout_root() -> Path | None:
    root = Path(__file__).resolve().parents[2]
    if (root / "bible_books.json").is_file() and (root / "index.json").is_file():
        return root
    return None


def _cache_path() -> Path:
    base = os.environ.get("XDG_CACHE_HOME") or Path.home() / ".cache"
    return Path(base) / "bible_resolver" / "bible_books.json"


def _fetch(url: str) -> bytes:
    with urllib.request.urlopen(url, timeout=FETCH_TIMEOUT) as response:
        return response.read()


def _expected_hash(index: dict) -> str | None:
    return index.get("meta", {}).get("books_sot", {}).get("hash")


def _parse(data: bytes) -> dict[str, int]:
    try:
        books = json.loads(data)["books"]
        return {name: entry["book_number"] for name, entry in books.items()}
    except (ValueError, KeyError, TypeError) as exc:
        raise BooksSotError(f"bible_books.json is malformed: {exc!r}") from exc


def _load_checkout(root: Path) -> dict[str, int]:
    data = (root / "bible_books.json").read_bytes()
    expected = _expected_hash(json.loads((root / "index.json").read_bytes()))
    if expected and content_hash(data) != expected:
        warnings.warn(
            f"bible_books.json differs from index.json (index {expected}, file "
            f"{content_hash(data)}); run scripts/generate_index.py",
            stacklevel=3,
        )
    return _parse(data)


def _load_remote() -> dict[str, int]:
    cache = _cache_path()
    try:
        data = _fetch(BOOKS_URL)
        expected = _expected_hash(json.loads(_fetch(INDEX_URL)))
    except OSError as exc:
        if cache.is_file():
            return _parse(cache.read_bytes())
        raise BooksSotError(
            f"cannot download {BOOKS_URL} and no cached copy exists: {exc}"
        ) from exc
    if expected and content_hash(data) != expected:
        raise BooksSotError(
            f"bible_books.json hash {content_hash(data)} does not match "
            f"index.json ({expected}); main is mid-update or the download is corrupt"
        )
    books = _parse(data)
    try:
        cache.parent.mkdir(parents=True, exist_ok=True)
        cache.write_bytes(data)
    except OSError:
        pass  # cache is best-effort
    return books


@lru_cache(maxsize=None)
def _load_path(path: str) -> dict[str, int]:
    return _parse(Path(path).read_bytes())


@lru_cache(maxsize=None)
def _load_default() -> dict[str, int]:
    root = _checkout_root()
    return _load_checkout(root) if root else _load_remote()


def load_books_sot(local_path: str | None = None) -> dict[str, int]:
    """Return the English book name -> canonical book number map."""
    return _load_path(str(local_path)) if local_path else _load_default()
