#!/usr/bin/env python3
"""
generate_index.py
─────────────────────────────────────────────────────────────────────────────
Reads bible_versions_config.yml + scans filesystem → writes index.json.

Validation rules:
  ERROR   config entry with no matching file on disk  → exit 1 (Action fails)
  WARNING file on disk with no config entry           → logged, not fatal

Run from repo root:
  python3 scripts/generate_index.py

Exit codes:
  0  → index.json written (or unchanged)
  1  → validation error — missing files detected
─────────────────────────────────────────────────────────────────────────────
"""

import json
import sys
import os
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    print("❌ PyYAML not found. Run: pip install pyyaml --break-system-packages")
    sys.exit(1)

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO_ROOT   = Path(__file__).parent.parent
CONFIG_PATH = REPO_ROOT / ".github" / "bible_versions_config.yml"
INDEX_PATH  = REPO_ROOT / "index.json"


def load_config() -> dict:
    if not CONFIG_PATH.exists():
        print(f"❌ Config not found: {CONFIG_PATH}")
        sys.exit(1)
    with open(CONFIG_PATH, encoding="utf-8") as f:
        return yaml.safe_load(f)


def scan_files() -> set[str]:
    """Returns set of relative paths: 'de/LU17_de.SQLite3.gz'"""
    found = set()
    for gz in REPO_ROOT.glob("*/*.SQLite3.gz"):
        lang_dir = gz.parent.name
        found.add(f"{lang_dir}/{gz.name}")
    return found


def validate(config_languages: dict, disk_files: set[str]) -> bool:
    """
    Compares config entries vs disk files.
    Returns True if clean, False if errors found.
    """
    errors   = []
    warnings = []

    # config → disk
    for lang, lang_data in config_languages.items():
        for version_id in lang_data["versions"]:
            expected_file = f"{lang}/{version_id}_{lang}.SQLite3.gz"
            if expected_file not in disk_files:
                errors.append(f"  MISSING FILE: {expected_file}  (declared in config)")

    # disk → config (orphan detection)
    declared_files = {
        f"{lang}/{vid}_{lang}.SQLite3.gz"
        for lang, ld in config_languages.items()
        for vid in ld["versions"]
    }
    for disk_file in sorted(disk_files):
        if disk_file not in declared_files:
            warnings.append(f"  ORPHAN FILE:  {disk_file}  (on disk, not in config)")

    for w in warnings:
        print(f"⚠️  {w}")
    for e in errors:
        print(f"❌ {e}")

    return len(errors) == 0


def build_index(config: dict) -> dict:
    base_url  = config["index"]["base_url"].rstrip("/")
    languages = config["languages"]

    out_languages = {}
    for lang, lang_data in languages.items():
        versions_out = {}
        for version_id, version_name in lang_data["versions"].items():
            filename = f"{version_id}_{lang}.SQLite3.gz"
            versions_out[version_id] = {
                "name": version_name,
                "file": filename,
                "url":  f"{base_url}/{lang}/{filename}",
            }

        out_languages[lang] = {
            "name":             lang_data["name"],
            "script":           lang_data["script"],
            "primary_version":  lang_data["primary_version"],
            "fallback_version": lang_data["fallback_version"],
            "reading_speed":    lang_data["reading_speed"],
            "versions":         versions_out,
        }

    return {
        "meta": {
            "version":  "1.0.0",
            "updated":  date.today().isoformat(),
            "note":     "Auto-generated by generate_index.py via sync_index.yml. Do NOT edit manually. Edit .github/bible_versions_config.yml to add versions.",
            "base_url": base_url,
        },
        "languages": out_languages,
    }


def write_if_changed(new_index: dict) -> bool:
    """Writes index.json only if content changed. Returns True if written."""
    new_content = json.dumps(new_index, ensure_ascii=False, indent=2) + "\n"

    if INDEX_PATH.exists():
        existing = INDEX_PATH.read_text(encoding="utf-8")
        # Ignore 'updated' date when comparing to avoid noisy commits
        existing_data = json.loads(existing)
        new_data_no_date = {**new_index, "meta": {**new_index["meta"], "updated": ""}}
        existing_no_date = {**existing_data, "meta": {**existing_data.get("meta", {}), "updated": ""}}
        if new_data_no_date == existing_no_date:
            print("✅ index.json unchanged — no commit needed")
            return False

    INDEX_PATH.write_text(new_content, encoding="utf-8")
    print(f"✅ index.json written → {INDEX_PATH}")
    return True


def main():
    print("─── generate_index.py ───────────────────────────────────")
    config     = load_config()
    disk_files = scan_files()

    print(f"📂 Found {len(disk_files)} SQLite files on disk")
    print(f"📋 Config declares {sum(len(ld['versions']) for ld in config['languages'].values())} versions across {len(config['languages'])} languages")

    if not validate(config["languages"], disk_files):
        print("\n❌ Validation failed — index.json NOT updated")
        sys.exit(1)

    new_index = build_index(config)
    write_if_changed(new_index)
    print("─────────────────────────────────────────────────────────")


if __name__ == "__main__":
    main()
